import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../core/localization/app_strings.dart';
import '../../core/theme/app_colors.dart';
import '../../core/widgets/empty_state.dart';
import '../marketplace/marketplace_repository.dart';

class NotificationsScreen extends ConsumerStatefulWidget {const NotificationsScreen({super.key});@override ConsumerState<NotificationsScreen> createState()=>_NotificationsScreenState();}
class _NotificationsScreenState extends ConsumerState<NotificationsScreen>{late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=ref.read(marketplaceRepositoryProvider).notifications();}void reload()=>setState(()=>future=ref.read(marketplaceRepositoryProvider).notifications());void open(Map<String,dynamic> n)async{await ref.read(marketplaceRepositoryProvider).markNotificationRead(n['id'].toString());final type=n['target_type']?.toString();final id=n['target_id']?.toString();if(!mounted)return;if(type=='order'&&id!=null)context.push('/orders/$id');else if(type=='request'&&id!=null)context.push('/request/$id/offers');else if(type=='conversation'&&id!=null)context.push('/chat/$id');else reload();}@override Widget build(BuildContext context){final s=AppStrings.of(context);return Scaffold(appBar:AppBar(title:Text(s.t('notifications')),actions:[TextButton(onPressed:()async{final items=await future;for(final n in items.where((x)=>x['is_read']!=true)){await ref.read(marketplaceRepositoryProvider).markNotificationRead(n['id'].toString());}reload();},child:Text(s.t('markAllRead')))]),body:FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,snap){if(snap.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(snap.hasError)return Center(child:FilledButton(onPressed:reload,child:Text(s.t('retry'))));final items=snap.data??[];if(items.isEmpty)return EmptyState(icon:Icons.notifications_none_rounded,title:s.t('noNotifications'));return RefreshIndicator(onRefresh:()async=>reload(),child:ListView.separated(padding:const EdgeInsets.all(18),itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){final n=items[i];final read=n['is_read']==true;return Card(color:read?Theme.of(context).cardColor:AppColors.blue.withValues(alpha:.08),child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:14,vertical:7),leading:Container(width:44,height:44,decoration:BoxDecoration(color:AppColors.blue.withValues(alpha:.08),borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.notifications_rounded,color:AppColors.blue)),title:Text((n['title_fallback']??n['title_key']??s.t('notifications')).toString(),style:TextStyle(fontWeight:read?FontWeight.w600:FontWeight.w800)),subtitle:Text((n['body_fallback']??n['body_key']??'').toString(),maxLines:2,overflow:TextOverflow.ellipsis),trailing:read?null:const CircleAvatar(radius:4,backgroundColor:AppColors.orange),onTap:()=>open(n)));}));}));}}